### ISSUE TITLE
Error: weibsup not available / phsup no available 

### ISSUE THREAD

**Issue by ghost** [goranbrostrom/eha#1]
Hi,

When I run the code line:
weibull.model0 <- weibreg(Surv(day, event)~strata(wood)+(familiar*sex*nsites), data=sqsurv.data, shape=0)

I get the following error:
Error in .C("weibsup", iter = as.integer(iter), as.double(control$eps),  : 
  "weibsup" not available for .C() for package "eha"

The eha library is present and loaded, and the R script as a whole worked perfectly with earlier versions of R and eha (I am now on R 3.4.3 "Kite-Eating Tree").  I have updated eha as well as R.

I note that you planned eventually to abandon eha::weibreg(), because the Weibull distribution is included in eha::phreg - but changing the code to:
weibull.model0 <- weibreg(Surv(day, event)~strata(wood)+(familiar*sex*nsites), data=sqsurv.data, shape=0)
...gives a similar error: 
Error in .C("phsup", iter = as.integer(iter), as.double(control$eps),  : 
  "phsup" not available for .C() for package "eha"

Would greatly appreciate help!

**Comment by goranbrostrom** [comment]
That's really weird: I see nothing like that on my end.  Could you send the output from 'sessionInfo()'?
However,I googled your error message (a good habit!)  and got a few hits: The advise was to reinstall 'eha' after upgrading R to 3.4.3, maybe with

> update.packages(checkBuilt = TRUE)

or

> install.packages("eha", checkBuilt = TRUE)

Göran

**Comment by ghost** [comment]
Dear Göran,
Thanks for your really swift response!  Session info attached, also the R script file that fails.

Following a decision in our institution to restrict local admin rights, R on my laptop has been having problems accessing its libraries, both when connected to our network and off-line.  So this might be a related issue.  However, following your reply, I have deleted and reinstalled both R 3.4.3 and my entire R library, and R seems to be finding all extra libraries OK, including eha - but it gets stuck on this “weibsup” issue.  As I mentioned, I am pretty certain my script is unaltered from 12 months ago, when it ran fine on the same data file.

In another script written 2 days ago, R creates a weibreg object OK (i.e. it seems to get past that weibsup hurdle), but then fails to find the function eha::plot.weibreg():
…
weibull.model1 <- weibreg(Surv(day, event)~siteyear, data=sqreenc.data, shape=0)
weibull.model3 <- weibreg(Surv(day, event)~strata(siteyear), data=sqreenc.data, shape=0)
…
plot.weibreg(weibull.model1, fn="haz", main="instantaneous hazard curves",xlab = "days",ylab="hazard function",xlim=c(0,40),
             ylim=c(0,0.3), yaxp=c(0,0.3,3), xaxs="r", yaxs="r", col="mediumvioletred", lwd=2, bty="n")
par(new=T)
plot.weibreg(weibull.model3, fn="haz", main="", xlab="",ylab="",lwd=2, xlim=c(0,40), ylim=c(0,0.3), col="olivedrab4",
             xaxs="r", yaxs="r", xaxt="n", yaxt="n")
…
This results in <<“Error in plot.weibreg(weibull.model1, fn = "haz", main = "instantaneous hazard curves",  :   could not find function "plot.weibreg">>

Many thanks for your time and help.  I’m fully prepared to learn that this is caused by some stupidity on my part, but I just can’t see it!

Jonathan


Dr Jonathan C. Reynolds
Game & Wildlife Conservation Trust
Burgate Manor
Fordingbridge
Hampshire   SP6 1EF
UK

Email:                    jreynolds@gwct.org.uk<mailto:jreynolds@gwct.org.uk>
Website:              www.gwct.org.uk<http://www.gwct.org.uk/>
Publications:      http://scholar.google.co.uk/citations?user=CPLe7WAAAAAJ&hl=en
Phone:                 +44(0)1425 652381 (switchboard)
                +44(0)1425 651033 (direct line)
                +44(0)7824 150507 (mobile)

**Comment by goranbrostrom** [comment]
Dear Jonathan,

if you have upgraded eha, _after_ upgrading R to 3.4.3, and set the flag 'checkBuilt=TRUE' at the eha upgrade, and it still doesn't work, I'm lost. Maybe you could ask at R-help?

Regarding the other issue, 'plot' is a generic function and 'plot.weibreg' is an instance, and it is _not exported_, i.e., invisible to the user: Just use 'plot'. (You can use 'eha:::plot.weibreg' to call it directly, but it is not recommended.)

Hope this helps,

Best, Göran

**Comment by goranbrostrom** [comment]
One second thought: Is it possible that you have two instances of eha installed?

**Comment by ghost** [comment]
Göran,

Thanks again for bothering about this.  It seems the fault must lie with me or my set-up.

Thanks for the advice about ‘plot.weibreg’ too.
Best regards,

Jonathan

**Comment by ghost** [comment]
Göran,
To complete the story for your peace of mind, I managed to get everything to run perfectly by moving the user personal library (ie the exact same files, not freshly installed) to my Desktop, and changing the R_LIBS_USER environmental variable in Control Panel to point to the new location.
I don't really understand why this worked, but it seems the problem was somehow related to access rights, which our IT people have monkeyed with recently.  What puzzles me most is why the eha library appeared to load, but failed to work.
Thanks again for your time - and of course for a very valuable library.
Jonathan

**Comment by ghost** [comment]
Göran,
To complete the story for your peace of mind, I managed to get everything to run perfectly by moving the user personal library (ie the same files, not freshly installed) to my Desktop, and changing the R_LIBS_USER environmental variable in Control Panel to point to the new location.
I don't fully understand why this worked, but it seems the problem was somehow related to access rights, which our IT people have monkeyed with recently.  What puzzles me most is why the eha library appeared to load, but failed to work.
Thanks again for your time - and of course for a very valuable library.
Jonathan



From: Jonathan Reynolds
Sent: Saturday, January 20, 3:18 PM
Subject: RE: [goranbrostrom/eha] Error: weibsup not available / phsup no available (#1)
To: goranbrostrom/eha

Göran,

Thanks again for bothering about this.  It seems the fault must lie with me or my set-up.

Thanks for the advice about 'plot.weibreg' too.
Best regards,

Jonathan
