### ISSUE TITLE
How can I extract the p-values from an `eha::weibreg` object?

### ISSUE THREAD

**Issue by zhengxiaoUVic** [goranbrostrom/eha#19]
Hello, "eha" users.

After fitting a fully parametric Cox proportional-hazards regression model using the `weibreg()` function from the "_eha_" package in R, how can I extract the _p_-values for the Wald tests of the regression coefficients?

```
library(eha) # v 2.11.5
fit <- weibreg(Surv(time, status) ~ sex, survival::lung, shape=1) # exponential baseline hazard function
```

I tried the usual method of using `summary(fit)$table[,5]`, but it didn’t work.
Any comments would be greatly appreciated.

**Comment by goranbrostrom** [comment]
Generally: 'weibreg' is superseeded by 'phreg' (see documentation), and with a fit from phreg you can do

> summary(fit)$coefficients[, 5]

Note: weibreg is not maintained, use phreg instead. See also 'aftreg', which in the Weibull case is identical (apart from parametrisation) to phreg.

**Comment by zhengxiaoUVic** [comment]
Thank you, Dr. Broström, for your prompt reply.

I initially chose `weibreg` over `phreg` because the former provides the _p_-value for the Wald test, while the latter offers that for the likelihood ratio test.

Additionally, when I extract the _p_-value from the `phreg` fit using `summary(fit_phreg)$coefficients`, it appears to correspond to the Wald test rather than the likelihood ratio test, as indicated by the output.

```
library(eha) # v 2.11.5
fit_weibreg <- weibreg(Surv(time, status) ~ sex, survival::lung, shape=1) # exponential baseline hazard function
fit_phreg <- phreg(Surv(time, status) ~ sex, survival::lung, dist="weibull", shape=1)

summary(fit_weibreg) # Wald test
summary(fit_phreg) # likelihood ratio test
summary(fit_phreg)$coefficients[,5] # p-value
```

![eha](https://github.com/user-attachments/assets/3540d164-8782-46c5-b3ac-aba39c89d25c)

**Comment by goranbrostrom** [comment]
Yes, 

summary(fit_phreg)$coefficients[, 5] 

gives the Wald p-value(s), while

drop1(fit_phreg, test = "Chisq")[-1, 4] 

gives the LR p-value(s).

**Comment by zhengxiaoUVic** [comment]
Thank you for the clarification, Dr. Broström.
