### ISSUE TITLE
predict/model.matrix for aftreg objects

### ISSUE THREAD

**Issue by adibender** [goranbrostrom/eha#2]
So I've read multiple times now, that eha doesn't provide functions for prediction for `aftreg` objects. 
Is there a specific reason for that? 
What would be a straight forward way to obtain the model matrix, variance-covariance matrix, perdictions, etc. in case of left-truncated data?

**Comment by adibender** [comment]
Ok, just realised, 
- model matrix can be obtained by specifying `x=TRUE` in the call to AFT and
- variance is stored in the `var` element of the `aftreg` output. 

So, what remains is, why no prediction function? Is it somehow not usefully defined for models with left-truncated data?

**Comment by goranbrostrom** [comment]
Answers:

First question: No.
Second question: I don't know (but see your own answer, or the code).
Third question: I haven't found it useful in my own research.
Fourth question: It certainly would be useful in some applications.
