### ISSUE TITLE
Nonparametric Estimation

### ISSUE THREAD

**Issue by w1806291** [goranbrostrom/eha#7]
Can anyone help me with this code? I have loaded the survival and eha packages.

par(mfrow = c(1, 2))
with(mort, plot(Surv(enter, exit, event), fn = "cum"))
with(mort, plot(Surv(enter, exit, event), fn = "surv"))

I get an error:

"fn" is not a graphical parameter
"fn" is not a graphical parameter
"fn" is not a graphical parameter
"fn" is not a graphical parameter
"fn" is not a graphical parameter
"fn" is not a graphical parameter

Thanks,

**Comment by goranbrostrom** [comment]
plot.Surv is a function in the survival package. It is a wrapper for plot.survfit, see its help page. You could try

with(mort, plot(Surv(enter, exit, event), fun = "cumhaz"))

etc. Göran

**Comment by w1806291** [comment]
Thanks that works!
